In [1]:
import pandas as pd
import calendar
import plotly.express as px

In [2]:
df = pd.read_csv('/Users/jackturek/Documents/Repos/SATX-Campaign-Finance/data/election25update.csv')
df.head(), df.columns

(    Report Id:                                              Name:  \
 0  View Report  Rudolph, Irina\n9706  Barons Creek\nSan Antoni...
 1  View Report  Chapa, Jacob\n9610  Limestone Pond\nSan Antoni...
 2  View Report  Chapa, Jacob\n9610  Limestone Pond\nSan Antoni...
 3  View Report  Garcia, Cesario\n7522  Riverside Park Dr\nSan ...
 4  View Report  Test Committee\n100  Military Plaza\nSan Anton...

   Contact Type:                           Report Type:  Amount:  \
 0   Contributor                                     UC   400.00
 1   Contributor                                     UC   200.00
 2   Contributor                                     UC    91.32
 3   Contributor                                     UC   200.00
 4   Expenditure  30th Day Before General Election 2023     0.00

                              strVal  Cand/Committee: Election Date:  Id  \
 0          Unexpended Contributions  Patricia Varela            NaN  50
 1          Unexpended Contributions  Patricia Varela            NaN  51
 2          Unexpended Contributions  Patricia Varela            NaN  52
 3          Unexpended Contributions  Patricia Varela            NaN  53
 4  Notice From Political Committees   Test Candidate       5/6/2023  82

    ReportId        FilerName Report Type Code:  Count:             TransDate:  \
 0      3048  Patricia Varela                 U       1   5/1/2023 12:00:00 AM
 1      3048  Patricia Varela                 U       2  3/31/2023 12:00:00 AM
 2      3048  Patricia Varela                 U       3   5/1/2023 12:00:00 AM
 3      3048  Patricia Varela                 U       4   4/3/2023 12:00:00 AM
 4      2934   Test Candidate                 C       5   3/8/2023 11:19:38 AM

              CreatedDt:  ZipCode  ReportLink
 0   5/5/2023 3:00:56 PM  78254.0         NaN
 1   5/5/2023 3:00:56 PM  78249.0         NaN
 2   5/5/2023 3:00:56 PM  78205.0         NaN
 3   5/5/2023 3:00:56 PM  78205.0         NaN
 4  3/8/2023 10:57:41 AM  78217.0         NaN  ,
 Index(['Report Id:', 'Name:', 'Contact Type:', 'Report Type:', 'Amount:',
        'strVal', 'Cand/Committee:', 'Election Date:', 'Id', 'ReportId',
        'FilerName', 'Report Type Code:', 'Count:', 'TransDate:', 'CreatedDt:',
        'ZipCode', 'ReportLink'],
       dtype='object'))

In [3]:
df['Election Date:'] = pd.to_datetime(df['Election Date:'], format='%m/%d/%y',
                                      errors='coerce')
df['TransDate:'] = pd.to_datetime(df['TransDate:'],
                                 errors='coerce')
df['CreatedDt:'] = pd.to_datetime(df['CreatedDt:'], 
                                  errors='coerce')
df.head()

/var/folders/h6/yxy6glj14rd2c83llgj50xnc0000gn/T/ipykernel_98117/2566515638.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['TransDate:'] = pd.to_datetime(df['TransDate:'],
/var/folders/h6/yxy6glj14rd2c83llgj50xnc0000gn/T/ipykernel_98117/2566515638.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['CreatedDt:'] = pd.to_datetime(df['CreatedDt:'],

,Report Id:,Name:,Contact Type:,Report Type:,Amount:,strVal,Cand/Committee:,Election Date:,Id,ReportId,FilerName,Report Type Code:,Count:,TransDate:,CreatedDt:,ZipCode,ReportLink
0,View Report,"Rudolph, Irina\n9706 Barons Creek\nSan Antoni...",Contributor,UC,400.00,Unexpended Contributions,Patricia Varela,NaT,50,3048,Patricia Varela,U,1,2023-05-01 00:00:00,2023-05-05 15:00:56,78254.0,NaN
1,View Report,"Chapa, Jacob\n9610 Limestone Pond\nSan Antoni...",Contributor,UC,200.00,Unexpended Contributions,Patricia Varela,NaT,51,3048,Patricia Varela,U,2,2023-03-31 00:00:00,2023-05-05 15:00:56,78249.0,NaN
2,View Report,"Chapa, Jacob\n9610 Limestone Pond\nSan Antoni...",Contributor,UC,91.32,Unexpended Contributions,Patricia Varela,NaT,52,3048,Patricia Varela,U,3,2023-05-01 00:00:00,2023-05-05 15:00:56,78205.0,NaN
3,View Report,"Garcia, Cesario\n7522 Riverside Park Dr\nSan ...",Contributor,UC,200.00,Unexpended Contributions,Patricia Varela,NaT,53,3048,Patricia Varela,U,4,2023-04-03 00:00:00,2023-05-05 15:00:56,78205.0,NaN
4,View Report,Test Committee\n100 Military Plaza\nSan Anton...,Expenditure,30th Day Before General Election 2023,0.00,Notice From Political Committees,Test Candidate,NaT,82,2934,Test Candidate,C,5,2023-03-08 11:19:38,2023-03-08 10:57:41,78217.0,NaN

In [4]:
df['TransDate:'] = df['TransDate:'].dt.normalize()
df['CreatedDt:'] = df['CreatedDt:'].dt.normalize()
df.head()

,Report Id:,Name:,Contact Type:,Report Type:,Amount:,strVal,Cand/Committee:,Election Date:,Id,ReportId,FilerName,Report Type Code:,Count:,TransDate:,CreatedDt:,ZipCode,ReportLink
0,View Report,"Rudolph, Irina\n9706 Barons Creek\nSan Antoni...",Contributor,UC,400.00,Unexpended Contributions,Patricia Varela,NaT,50,3048,Patricia Varela,U,1,2023-05-01,2023-05-05,78254.0,NaN
1,View Report,"Chapa, Jacob\n9610 Limestone Pond\nSan Antoni...",Contributor,UC,200.00,Unexpended Contributions,Patricia Varela,NaT,51,3048,Patricia Varela,U,2,2023-03-31,2023-05-05,78249.0,NaN
2,View Report,"Chapa, Jacob\n9610 Limestone Pond\nSan Antoni...",Contributor,UC,91.32,Unexpended Contributions,Patricia Varela,NaT,52,3048,Patricia Varela,U,3,2023-05-01,2023-05-05,78205.0,NaN
3,View Report,"Garcia, Cesario\n7522 Riverside Park Dr\nSan ...",Contributor,UC,200.00,Unexpended Contributions,Patricia Varela,NaT,53,3048,Patricia Varela,U,4,2023-04-03,2023-05-05,78205.0,NaN
4,View Report,Test Committee\n100 Military Plaza\nSan Anton...,Expenditure,30th Day Before General Election 2023,0.00,Notice From Political Committees,Test Candidate,NaT,82,2934,Test Candidate,C,5,2023-03-08,2023-03-08,78217.0,NaN

In [5]:
# Create new cols for Election, Trans, Created calendar
df['Election Year'] = df['Election Date:'].dt.year
df['Election Month'] = df['Election Date:'].dt.month
df['Election Day'] = df['Election Date:'].dt.day

# Break down CreatedDt into Year, Month, Day
df['Created Year'] = df['CreatedDt:'].dt.year
df['Created Month'] = df['CreatedDt:'].dt.month
df['Created Day'] = df['CreatedDt:'].dt.day

# Break down TransDate into Year, Month, Day
df['Trans Year'] = df['TransDate:'].dt.year
df['Trans Month'] = df['TransDate:'].dt.month
df['Trans Day'] = df['TransDate:'].dt.day

In [6]:
# Map month numbers to month names
df['Election Month'] = df['Election Month'].apply(lambda x: calendar.month_name[int(x)] if pd.notnull(x) else None)
df['Created Month'] = df['Created Month'].apply(lambda x: calendar.month_name[int(x)] if pd.notnull(x) else None)
df['Trans Month'] = df['Trans Month'].apply(lambda x: calendar.month_name[int(x)] if pd.notnull(x) else None)

# Convert year and day cols to integers
df['Election Year'] = df['Election Year'].astype('Int64')
df['Election Day'] = df['Election Day'].astype('Int64')
df['Created Year'] = df['Created Year'].astype('Int64')
df['Created Day'] = df['Created Day'].astype('Int64')
df['Trans Year'] = df['Trans Year'].astype('Int64')
df['Trans Day'] = df['Trans Day'].astype('Int64')

df.head()

,Report Id:,Name:,Contact Type:,Report Type:,Amount:,strVal,Cand/Committee:,Election Date:,Id,ReportId,...,ReportLink,Election Year,Election Month,Election Day,Created Year,Created Month,Created Day,Trans Year,Trans Month,Trans Day
0,View Report,Mark ODonnell Campaign,Expenditure,January 15: Semi-Annual 2025,0.0,Notice From Political Committees,Mark ODonnell,2025-05-03,99.0,3236.0,...,https://webapp5.sanantonio.gov/CampFinHistoric...,2025,May,3,2025,January,15,2025,January,15
1,View Report,"Courage, John",Lender,April 15 Quarterly 2024,25000.0,Loans,John Courage,NaT,551.0,3153.0,...,https://webapp5.sanantonio.gov/CampFinHistoric...,<NA>,None,<NA>,2024,April,13,2024,February,28
2,View Report,"Courage, John",Lender,July 15: Semi-Annual 2024,25000.0,Loans,John Courage,2025-05-03,552.0,3168.0,...,https://webapp5.sanantonio.gov/CampFinHistoric...,2025,May,3,2024,July,9,2024,February,28
3,View Report,"Altamirano, Alberto",Lender,July 15: Semi-Annual 2024,15000.0,Loans,Alberto Altamirano,2025-05-03,553.0,3173.0,...,https://webapp5.sanantonio.gov/CampFinHistoric...,2025,May,3,2024,July,12,2024,April,30
4,View Report,"Altamirano, Alberto",Lender,July 15: Semi-Annual 2024,35000.0,Loans,Alberto Altamirano,2025-05-03,554.0,3173.0,...,https://webapp5.sanantonio.gov/CampFinHistoric...,2025,May,3,2024,July,12,2024,May,16

In [6]:
# Fix Manny Pelaez name
df['Cand/Committee:'] = df['Cand/Committee:'].replace({
    'Manny Pelaez Pelaez': 'Manny Pelaez',
    'Manuel Pelaez': 'Manny Pelaez'
})

df['FilerName'] = df['FilerName'].replace({
    'Manny Pelaez Pelaez': 'Manny Pelaez',
    'Manuel Pelaez': 'Manny Pelaez'
})

# Fix Clayton Perry name
df['FilerName'] = df['FilerName'].replace({
    'CLAYTON PERRY': 'Clayton Perry'
})

df['Cand/Committee:'] = df['Cand/Committee:'].replace({
    'CLAYTON PERRY': 'Clayton Perry'
})

df['Cand/Committee:'].unique()
df['FilerName'].unique()

array(['Patricia Varela', 'Test Candidate', 'Bryan Martin',
       'Marina Gavito', 'Sukh Kaur', 'Marc Whyte', 'Mario Bravo',
       'Mark ODonnell', 'Bobby Herrera', 'Cindy Onyekwelu',
       'Denise Gutierrez', 'Joel Solis', 'Christopher Schuchardt',
       'Ray Basaldua', 'Ernest Salinas', 'Rose Requenez Hill',
       'Gregorio De La Paz', 'Christopher Longoria', 'Robert Flores',
       'Jeremy Roberts', 'Erin Gallegos Reid', 'Daniel Rossiter',
       'Sandragrace Martinez', 'Andrew Luck', 'Armando Dominguez',
       'John Courage', 'Alberto Altamirano', 'Sakib Shaikh',
       'John Atwood', 'Paula McGee', 'Rolando Pablos', 'Misty Spears',
       'Patty Gibbons', 'Andrew Vicencio', 'Clayton Perry',
       'Gerald Lopez', 'Ramiro Gonzales', 'Santos Alvarado',
       'Manny Pelaez', 'Julisa Medrano-Guerra', 'Kelly Gonzalez',
       'Carla Sisco', 'Irina Rudolph', 'LARRY LA ROSE', 'Patrick Jones',
       'Michael Samaniego', 'cesario garcia', 'David Lara',
       'Jalen McKee-Rodriguez', 'SA Justice Charter PAC', 'Jacob Chapa',
       'Protect SA PAC', 'San Antonio Safe PAC',
       'San Antonio Justice Charter PAC', 'Jarrett Lipman',
       'Richard Otley', 'Arturo Espinosa', 'Margaret Sherwood',
       'Ronald Nirenberg', 'Edward Giles', 'Carla Walker',
       'Phyllis Viagran', 'Adriana Garcia', 'Melissa Cabello Havrda',
       'Armando Bravo', 'Chris Baecker', 'Teri Castillo', 'Rudy Lopez',
       'Madison Gutierrez', 'San Antonio Equity Alliance', 'Gary Allen',
       'IRINA RUDOLPH', 'Patricia Varela City Council Candidate',
       'Diana Uriegas', 'James Guild', 'Ana Sandoval', 'Denise McVea',
       'Patrick Von Dohlen', 'Ivalis Gonzalez', 'Angela Aramburu',
       'Renew San Antonio', 'Vote Against Prop C',
       'Elect Democratic Women FEC ID C00685297', 'Gina Ortiz Jones',
       'Timmy Westley', 'Edward Mungia', 'Norma Cavazos',
       'Lawson Alaniz - Picasso', 'Christopher Reyes', 'Trinity Haddox',
       'Ric Galvan', 'Jose Martinez', 'Vanessa Chavez',
       'Ernest Arrellano', 'Anita Kegley', 'Emily Garza', 'Kizzie Thomas',
       'Robert Melvin', 'robert salinas', 'Eric Litaker',
       'Rose Requenez-Hill', 'April Chang', 'Daniel Mezza',
       'Pablo Arriaga', 'Gina Jones', 'Roy Anthony', 'Cynthia Alderete',
       'Arnulfo Ortiz', 'April Guadarrama',
       'San Antonio Police Officers Association PAC', 'Johnathon Cruz',
       'Gerardo Zambrano', 'Matthew Gauna', 'Mauricio Sanchez',
       'Stephanie Powell', 'Adriana Rocha Garcia', 'Kenneth Thomas',
       'Dominique Littwitz', 'James Melvin', 'Celeste Tidwell',
       'Raymond Zavala', 'Brandon Gonzales', 'Cesario Garcia',
       'Roberto Rios Ortega'], dtype=object)

In [ ]:
# # Filter only for TransDate 10/27/2024 and later
# df = df[df['TransDate:'] >= '2024-10-27']
# df.head()

,Report Id:,Name:,Contact Type:,Report Type:,Amount:,strVal,Cand/Committee:,Election Date:,Id,ReportId,...,ReportLink,Election Year,Election Month,Election Day,Created Year,Created Month,Created Day,Trans Year,Trans Month,Trans Day
0,View Report,Mark ODonnell Campaign,Expenditure,January 15: Semi-Annual 2025,0.0,Notice From Political Committees,Mark ODonnell,2025-05-03,99.0,3236.0,...,https://webapp5.sanantonio.gov/CampFinHistoric...,2025,May,3,2025,January,15,2025,January,15
22,View Report,"Atwood, John",Lender,January 15: Semi-Annual 2025,700.0,Loans,John Atwood,2025-05-03,578.0,3196.0,...,https://webapp5.sanantonio.gov/CampFinHistoric...,2025,May,3,2025,January,1,2024,October,29
23,View Report,"Atwood, John",Lender,January 15: Semi-Annual 2025,380.0,Loans,John Atwood,2025-05-03,579.0,3196.0,...,https://webapp5.sanantonio.gov/CampFinHistoric...,2025,May,3,2025,January,1,2024,November,8
24,View Report,"Atwood, John",Lender,January 15: Semi-Annual 2025,330.0,Loans,John Atwood,2025-05-03,580.0,3196.0,...,https://webapp5.sanantonio.gov/CampFinHistoric...,2025,May,3,2025,January,1,2024,November,23
25,View Report,"Atwood, John",Lender,January 15: Semi-Annual 2025,100.0,Loans,John Atwood,2025-05-03,581.0,3196.0,...,https://webapp5.sanantonio.gov/CampFinHistoric...,2025,May,3,2025,January,1,2024,December,19

In [7]:
df.to_csv('election25update.csv', index=False)